layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

# decoupling page from github variables
email: echandifelipe@gmail.com
bio: Constantly checking my assumptions. #Anwers the question: Who am I?
name: Felipe Echandi
why: I deeply care about improving people's lives with my work, which fuels me to improve myself.      #Answers the question: Para qué hago lo que hago?
what: I co-founded <a href="https://web.cuanto.app/en" {% if site.style == 'dark' %}class="text-white"{% endif %}>Cuanto</a> (YCW19) to give Latin American creators a chance to live from the internet. #Answers the question: Que hago?

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: felcheck
  keybase: felcheck
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: felcheck
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

#leave topics for lists for the future
#topics:
  #- name: CSS
    #web_url: https://github.com/topics/css
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  #- name: Web design

  #- name: Sass
    #web_url: https://github.com/topics/sass
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
